### ISSUE TITLE
cmake error on Android

### ISSUE THREAD

**Issue by BaiShisheng** [rupeshs/alpaca.cpp#2]
I followed the instructions in the documentation on my Android phone, and I got the following error, it seems that the first step of mkdir is not in the right place, I hope someone will guide me how to solve it

CMake Error: The source directory "/data/data/com.termux/files/home" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by mohammedfatihX** [comment]
I guess you should run the cmake... command in side the alpaca.cpp folder

**Comment by rupeshs** [comment]
@BaiShisheng You need to build Android executable on a Linux machine with NDK and copy the executable to Android device. I think you are trying to build inside termux.
