### ISSUE TITLE
Advice to build for Android under Windows

### ISSUE THREAD

**Issue by schorhr** [rupeshs/alpaca.cpp#4]
Sorry if this is not the right place to ask, but I'm trying to follow the guide to build for android. 
I'm on Windows 10 so I have used SET instead of export for the path variable, and %NKD% instead of $NKS.
I have also tried to just paste the direct path instead of using the variable.

I have never used cmake before. Got other llama/alpaca projects to work. 

I would apreceate any help, thank you!
 
 
C:\Users\AE\Downloads\alpaca.cpp-master\alpaca.cpp-master\build-android>cmake -DCMAKE_TOOLCHAIN_FILE=%NDK%\build\cmake\android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-23 -DCMAKE_C_FLAGS=-march=armv8.4a+dotprod ..
CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:
 
    C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe
 
  to get the value of VCTargetsPath:
 
    MSBuild version 17.5.1+f6fdcf537 for .NET Framework
    Der Buildvorgang wurde am 23.03.2023 19:41:40 gestartet.
    Included response file: C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\MSBuild.rsp
 
    Projekt "C:\Users\AE\Downloads\alpaca.cpp-master\alpaca.cpp-master\build-android\CMakeFiles\3.26.1\VCTargetsPath.vcxproj" auf Knoten "1" (Standardziele).
    C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(832,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Users\AE\Downloads\alpaca.cpp-master\alpaca.cpp-master\build-android\CMakeFiles\3.26.1\VCTargetsPath.vcxproj]
    Die Erstellung des Projekts "C:\Users\AE\Downloads\alpaca.cpp-master\alpaca.cpp-master\build-android\CMakeFiles\3.26.1\VCTargetsPath.vcxproj" ist abgeschlossen (Standardziele) -- FEHLER.
 
    Fehler beim Buildvorgang. == ERROR DURING BUILDING PROCESS
 
    "C:\Users\AE\Downloads\alpaca.cpp-master\alpaca.cpp-master\build-android\CMakeFiles\3.26.1\VCTargetsPath.vcxproj" (Standardziel) (1) ->
    (_CheckForInvalidConfigurationAndPlatform Ziel) ->
      C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(832,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Users\AE\Downloads\alpaca.cpp-master\alpaca.cpp-master\build-android\CMakeFiles\3.26.1\VCTargetsPath.vcxproj]
 
        0 Warnung(en) ==WARNINGS
        1 Fehler  == ERRORS
 
    Verstrichene Zeit 00:00:01.31
 
 
  Exit code: 1
 
 
 
-- Configuring incomplete, errors occurred!

(I know the path alpaca.cpp-master\alpaca.cpp-master\ is source for many headaches, but as I made multiple sub folders to get everything to work, I stuck with it. Sorry!)

**Comment by rupeshs** [comment]
It would be better to use Linux for the android build. Windows build you might need to set up clang and NDK properly.
